Module2 task3
htmlacademy-adaptive/1728289-cat-energy-22 pull request #6
Opened 2021-03-26 20:40 UTC by VladimirRys

2021-03-26 21:15 UTC, baileys-li requested changes

2021-03-26 21:15 UTC, baileys-li commented on source/catalog.html
> +    <a href="/source/catalog.html" class="page-header__logo logo-section">
Не, не надо. Пусть на главную ведёт

2021-03-26 21:15 UTC, baileys-li commented on source/catalog.html
> +              </form>
Форма тут не нужна. Просто ссылка

2021-03-26 21:15 UTC, baileys-li commented on source/catalog.html
> +              <caption class="table__title">Cat Energy PRO 500 г</caption>
хвалю за caption

2021-03-26 21:15 UTC, baileys-li commented on source/catalog.html
> +              </form>
Форма вообще не к месту. Сделай ссылкой и вынеси из таблицы

2021-03-26 21:15 UTC, baileys-li commented on source/catalog.html
> +              </form>
И не в таблице. Отдельно

2021-03-26 21:15 UTC, baileys-li commented on source/catalog.html
> +      <div class="promo__wrapper">
Ссылка

2021-03-26 21:15 UTC, baileys-li commented on source/catalog.html
> +        <p class="promo__icon"><img src="img/icon/icon_gift.svg" alt="Подарок" width="78" height="80"></p>
Картинка же перед текстом

2021-03-26 21:22 UTC, VladimirRys commented on source/catalog.html
> +      <div class="promo__wrapper">
???

2021-03-26 21:29 UTC, VladimirRys commented on source/catalog.html
> +      <div class="promo__wrapper">
ааа догнал

2021-03-26 21:52 UTC, baileys-li requested changes

2021-03-26 21:52 UTC, baileys-li commented on source/catalog.html
> +            <p class="table__button button"><input type="button" value="заказать"></p>
Да поменяй `input[type="button"]` на ссылки

2021-03-26 21:52 UTC, baileys-li commented on source/catalog.html
> +          <li class="site-list__item">
тут кстати эта страница `.site-list__item--active`, а не главная

2021-03-27 09:19 UTC, baileys-li requested changes

2021-03-27 09:19 UTC, baileys-li commented on source/catalog.html
> +            <a href="#" class="table__button button"><input type="button" value="заказать"></a>
Ладно, я не так выразился. Тебе не нужен `input[type="button"]`, его и нужно было заменить на ссылку.

2021-03-27 13:31 UTC, merged